spring:
  data:
    mongodb:
      uri: mongodb+srv://${DB_USER:admin}:${DB_PASSWORD}@webfluxclustercourse.hg7iy.mongodb.net/${DB_NAME:webflux-course}?retryWrites=true&w=majority&appName=WebFluxClusterCourse
